# Use container based environment, slightly faster than standard
sudo: true

# language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      #- gcc-4.8
      #- g++-4.8
      - wget
      # Package list from http://bazel.io/docs/install.html
      - oraclejdk8
      - pkg-config
      - zip
      - zlib1g-dev

install:
  - ./install-bazel.sh
  - wget https://raw.githubusercontent.com/mzhaom/lrte/master/install-release.sh && sudo bash install-release.sh

script:
  # The kernel used by travis is too old to allow namespace creation
  # for normal account, so we disable it.
  - bazel --batch build --crosstool_top=//tools/lrte:toolchain --spawn_strategy=standalone --genrule_strategy=standalone //examples/...:all
  - bazel --batch test --crosstool_top=//tools/lrte:toolchain --spawn_strategy=standalone //examples/...:all //third_party/gperftools:all

notifications:
  email: false
